services:
  - type: web
    name: weather-app-django
    env: python
    buildCommand: ./build.sh
    startCommand: cd /opt/render/project/src && gunicorn weather_project.wsgi:application --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: weather_project.settings
      - key: WEATHERAPI_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false 